<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Maquinaria;

class MaquinariaSeeder extends Seeder
{
    public function run(): void
    {
        $maquinaria = [
            [
                'codigo' => 'MAQ-EXC-0001',
                'numero_serie' => 'CAT320-2022-001',
                'nombre' => 'Excavadora Hidráulica CAT 320',
                'tipo' => 'excavadora',
                'marca' => 'Caterpillar',
                'modelo' => '320',
                'año' => 2022,
                'descripcion' => 'Excavadora hidráulica de 20 toneladas, ideal para construcción y minería',
                'capacidad' => '20 toneladas',
                'peso' => 20000.00,
                'dimensiones' => json_encode(['largo' => '9.5m', 'ancho' => '2.8m', 'alto' => '3.1m']),
                'especificaciones' => json_encode(['potencia' => '121 HP', 'alcance' => '9.5m']),
                'combustible' => 'diesel',
                'consumo_promedio' => 18.5,
                'disponibilidad' => 'disponible',
                'estado' => 'excelente',
                'tarifa_hora' => 180.00,
                'tarifa_dia' => 1200.00,
                'tarifa_semana' => 7500.00,
                'tarifa_mes' => 28000.00,
                'ubicacion_actual' => 'Lima - Sede Principal',
                'imagenes' => json_encode(['excavadora-cat-320.jpg']),
                'certificaciones' => json_encode(['ISO 9001', 'CE']),
            ],
            [
                'codigo' => 'MAQ-EXC-0002',
                'numero_serie' => 'VOL-EC210-2021-001',
                'nombre' => 'Excavadora Volvo EC210',
                'tipo' => 'excavadora',
                'marca' => 'Volvo',
                'modelo' => 'EC210',
                'año' => 2021,
                'descripcion' => 'Excavadora de última generación con tecnología ECO',
                'capacidad' => '21 toneladas',
                'peso' => 21500.00,
                'dimensiones' => json_encode(['largo' => '10m', 'ancho' => '3m', 'alto' => '3.2m']),
                'especificaciones' => json_encode(['potencia' => '145 HP', 'sistema' => 'ECO']),
                'combustible' => 'diesel',
                'consumo_promedio' => 17.5,
                'disponibilidad' => 'disponible',
                'estado' => 'excelente',
                'tarifa_hora' => 190.00,
                'tarifa_dia' => 1300.00,
                'tarifa_semana' => 8000.00,
                'tarifa_mes' => 30000.00,
                'ubicacion_actual' => 'Lima - Sede Principal',
                'imagenes' => json_encode(['excavadora-volvo-ec210.jpg']),
                'certificaciones' => json_encode(['ISO 9001', 'CE']),
            ],
            [
                'codigo' => 'MAQ-CAR-0001',
                'numero_serie' => 'CAT950-2023-001',
                'nombre' => 'Cargador Frontal CAT 950',
                'tipo' => 'cargador',
                'marca' => 'Caterpillar',
                'modelo' => '950',
                'año' => 2023,
                'descripcion' => 'Cargador frontal de ruedas para movimiento de tierras',
                'capacidad' => '3.5 m³',
                'peso' => 17000.00,
                'dimensiones' => json_encode(['largo' => '8m', 'ancho' => '2.9m', 'alto' => '3.5m']),
                'especificaciones' => json_encode(['potencia' => '195 HP', 'capacidad_cucharon' => '3.5m³']),
                'combustible' => 'diesel',
                'consumo_promedio' => 16.0,
                'disponibilidad' => 'disponible',
                'estado' => 'excelente',
                'tarifa_hora' => 160.00,
                'tarifa_dia' => 1100.00,
                'tarifa_semana' => 6800.00,
                'tarifa_mes' => 25000.00,
                'ubicacion_actual' => 'Lima - Sede Principal',
                'imagenes' => json_encode(['cargador-cat-950.jpg']),
                'certificaciones' => json_encode(['ISO 9001']),
            ],
            [
                'codigo' => 'MAQ-CAM-0001',
                'numero_serie' => 'VOL-FM440-2022-001',
                'nombre' => 'Camión Volquete Volvo FM 440',
                'tipo' => 'camion',
                'marca' => 'Volvo',
                'modelo' => 'FM 440',
                'año' => 2022,
                'descripcion' => 'Volquete pesado de 25 m³ para transporte de materiales',
                'capacidad' => '25 m³',
                'peso' => 18000.00,
                'dimensiones' => json_encode(['largo' => '9m', 'ancho' => '2.5m', 'alto' => '3.8m']),
                'especificaciones' => json_encode(['potencia' => '440 HP', 'capacidad_carga' => '25m³']),
                'combustible' => 'diesel',
                'consumo_promedio' => 28.0,
                'disponibilidad' => 'disponible',
                'estado' => 'bueno',
                'tarifa_hora' => 140.00,
                'tarifa_dia' => 950.00,
                'tarifa_semana' => 5800.00,
                'tarifa_mes' => 22000.00,
                'ubicacion_actual' => 'Lima - Sede Principal',
                'imagenes' => json_encode(['volquete-volvo-fm440.jpg']),
                'certificaciones' => json_encode(['ISO 9001']),
            ],
            [
                'codigo' => 'MAQ-BUL-0001',
                'numero_serie' => 'CAT140-2021-001',
                'nombre' => 'Motoniveladora CAT 140',
                'tipo' => 'bulldozer',
                'marca' => 'Caterpillar',
                'modelo' => '140',
                'año' => 2021,
                'descripcion' => 'Motoniveladora para nivelación de terrenos y carreteras',
                'capacidad' => '3.7m ancho de hoja',
                'peso' => 15900.00,
                'dimensiones' => json_encode(['largo' => '8.8m', 'ancho' => '2.6m', 'alto' => '3.4m']),
                'especificaciones' => json_encode(['potencia' => '165 HP', 'ancho_hoja' => '3.7m']),
                'combustible' => 'diesel',
                'consumo_promedio' => 15.5,
                'disponibilidad' => 'disponible',
                'estado' => 'bueno',
                'tarifa_hora' => 170.00,
                'tarifa_dia' => 1150.00,
                'tarifa_semana' => 7000.00,
                'tarifa_mes' => 26500.00,
                'ubicacion_actual' => 'Lima - Sede Principal',
                'imagenes' => json_encode(['motoniveladora-cat-140.jpg']),
                'certificaciones' => json_encode(['ISO 9001']),
            ],
            [
                'codigo' => 'MAQ-COM-0001',
                'numero_serie' => 'HAM3411-2023-001',
                'nombre' => 'Rodillo Compactador Hamm 3411',
                'tipo' => 'compactador',
                'marca' => 'Hamm',
                'modelo' => '3411',
                'año' => 2023,
                'descripcion' => 'Rodillo compactador vibratorio para asfalto y suelos',
                'capacidad' => '2.1m ancho de rodillo',
                'peso' => 11500.00,
                'dimensiones' => json_encode(['largo' => '5.2m', 'ancho' => '2.1m', 'alto' => '3m']),
                'especificaciones' => json_encode(['potencia' => '98 HP', 'ancho_rodillo' => '2.1m']),
                'combustible' => 'diesel',
                'consumo_promedio' => 12.0,
                'disponibilidad' => 'disponible',
                'estado' => 'excelente',
                'tarifa_hora' => 120.00,
                'tarifa_dia' => 850.00,
                'tarifa_semana' => 5200.00,
                'tarifa_mes' => 19500.00,
                'ubicacion_actual' => 'Lima - Sede Principal',
                'imagenes' => json_encode(['compactadora-hamm-3411.jpg']),
                'certificaciones' => json_encode(['ISO 9001', 'CE']),
            ],
        ];

        foreach ($maquinaria as $equipo) {
            Maquinaria::create($equipo);
        }

        $this->command->info('✓ Maquinaria creada exitosamente');
        $this->command->info('  ' . count($maquinaria) . ' equipos registrados');
    }
}
